import { LocationType } from '../types/suburb';

export const AUSTRALIAN_STATES = [
  {
    id: 'SUBURB#NSW',
    state: 'NSW',
    locationType: LocationType.STATE,
    region: '',
    suburb: 'New South Wales',
    postcode: '',
    geohash: '',
  },
  {
    id: 'SUBURB#VIC',
    state: 'VIC',
    locationType: LocationType.STATE,
    region: '',
    suburb: 'Victoria',
    postcode: '',
    geohash: '',
  },
  {
    id: 'SUBURB#QLD',
    state: 'QLD',
    locationType: LocationType.STATE,
    region: '',
    suburb: 'Queensland',
    postcode: '',
    geohash: '',
  },
  {
    id: 'SUBURB#SA',
    state: 'SA',
    locationType: LocationType.STATE,
    region: '',
    suburb: 'South Australia',
    postcode: '',
    geohash: '',
  },
  {
    id: 'SUBURB#WA',
    state: 'WA',
    locationType: LocationType.STATE,
    region: '',
    suburb: 'Western Australia',
    postcode: '',
    geohash: '',
  },
  {
    id: 'SUBURB#TAS',
    state: 'TAS',
    locationType: LocationType.STATE,
    region: '',
    suburb: 'Tasmania',
    postcode: '',
    geohash: '',
  },
  {
    id: 'SUBURB#NT',
    state: 'NT',
    locationType: LocationType.STATE,
    region: '',
    suburb: 'Northern Territory',
    postcode: '',
    geohash: '',
  },
  {
    id: 'SUBURB#ACT',
    state: 'ACT',
    locationType: LocationType.STATE,
    region: '',
    suburb: 'Australian Capital Territory',
    postcode: '',
    geohash: '',
  },
];
